---
hwi_oauth:
    firewall_name: 'main'
    
    resource_owners:
        github:
            type: 'github'
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            scope: 'user:email'
            
    connect:
        confirmation: false
        account_connector: App\Security\User\AccountConnector