services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    developtech.organization_manager:
        class: AppBundle\Manager\OrganizationManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@developtech.slugger"

    developtech.user_manager:
        class: AppBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.password_encoder"
            - "@translator"
            - "@developtech.activation_link_manager"

    developtech.user_provider:
        class: AppBundle\Security\User\Provider\UserProvider
        arguments:
            - "@developtech.user_manager"

    developtech.authentication_manager:
        class: AppBundle\Security\Authentication\AuthenticationManager
        arguments:
            - "@request_stack"
            - "@security.token_storage"
            - "@security.encoder_factory"
            - "@security.user_checker.main"
            - "@session"
            - "@developtech.user_provider"
            - "@event_dispatcher"
            - "main"

    developtech.authentication_handler:
        class: AppBundle\Security\Authentication\AuthenticationHandler
        arguments:
            - "@session"
            - "@router"
            - "@translator"

    developtech.activation_link_manager:
        class: AppBundle\Manager\ActivationLinkManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@developtech.mailer"

    developtech.slugger:
        class: AppBundle\Utils\Slugger

    developtech.mailer:
        class: AppBundle\Utils\Mailer
        arguments:
            - "@swiftmailer.mailer"
            - "@translator"
            - "%website_url%"
            - "%website_mail%"
            - "%mail_name%"

    developtech.project_subscriber:
        class: AppBundle\Subscriber\ProjectSubscriber
        tags:
            - {name: kernel.event_subscriber}